
jobs:

#####
# Libraries

- name: TypeUtilsAPI
  deploy:
    contract: TypeUtilsImpl.bin

- name: ArrayUtilsAPI
  deploy:
    contract: ArrayUtilsImpl.bin

#####
# TypeUtils Test
- name: TypeUtilsLibTest
  deploy:
    contract: TypeUtilsTest.bin
    instance: TypeUtilsTest
    libraries: TypeUtilsAPI:$TypeUtilsAPI

# contentLength bytes32
- name: testLengthBytes32
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testLengthBytes32

- name: assertLengthBytes32
  assert:
    key: $testLengthBytes32
    relation: eq
    val: success

# isEmpty
- name: testIsEmpty
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testIsEmpty

- name: assertIsEmpty
  assert:
    key: $testIsEmpty
    relation: eq
    val: success

# uint -> bytes32
- name: testUintToBytes32
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testUintToBytes32

- name: assertUintToBytes32
  assert:
    key: $testUintToBytes32
    relation: eq
    val: success

# bytes32 -> string
- name: testBytes32ToString
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testBytes32ToString

- name: assertBytes32ToString
  assert:
    key: $testBytes32ToString
    relation: eq
    val: success

# string -> bytes32
- name: testStringToBytes32
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testStringToBytes32

- name: assertStringToBytes32
  assert:
    key: $testStringToBytes32
    relation: eq
    val: success

# bytes -> bytes32
- name: testBytesToBytes32
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testBytesToBytes32

- name: assertBytesToBytes32
  assert:
    key: $testBytesToBytes32
    relation: eq
    val: success

# bytes -> uint
- name: testBytesToUint
  call:
    destination: $TypeUtilsLibTest
    bin: TypeUtilsTest
    function: testBytesToUint

- name: assertBytesToUint
  assert:
    key: $testBytesToUint
    relation: eq
    val: success

#####
# ArrayUtils Test
- name: ArrayUtilsLibTest
  deploy:
    contract: ArrayUtilsTest.bin
    instance: ArrayUtilsTest
    libraries: ArrayUtilsAPI:$ArrayUtilsAPI

- name: testContainsBytes32
  call:
    destination: $ArrayUtilsLibTest
    bin: ArrayUtilsTest
    function: testContainsBytes32

- name: assertContainsBytes32
  assert:
    key: $testContainsBytes32
    relation: eq
    val: success
